name: bands

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_APP_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_APP_USER_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  backend:
    container_name: backend
    user: "appuser"
    image: riccardocmp/bands-backend:latest
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      APP_ENVIRONMENT: "PRODUCTION"
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: 0
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_APP_USERNAME: ${DATABASE_APP_USERNAME}
      DATABASE_APP_USER_PASSWORD: ${DATABASE_APP_USER_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: "localhost"
      USE_SSL: ${USE_SSL}
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
  frontend:
    container_name: bands-app
    image: riccardocmp/bands-frontend:latest
    ports:
      - ${FRONTEND_APP_PORT}:80
    depends_on:
      - backend
volumes:
  db_data: