[tool.poetry]
name = "bands_backend"
version = "0.1.0"
description = ""
authors = ["Riccardo Campo <riccardocampo@tutanota.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
