# Generated by Django 5.1 on 2024-10-23 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import bands.models_extensions


class Migration(migrations.Migration):
    """
    Initial migration.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", bands.models_extensions.PositiveAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("spotify_url", models.CharField(max_length=2000)),
                ("image_url", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "artist",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", bands.models_extensions.PositiveAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    bands.models_extensions.PositiveTinyIntegerField(choices=[(0, "flag"), (1, "value")], default=0),
                ),
                (
                    "category",
                    bands.models_extensions.PositiveTinyIntegerField(
                        choices=[(0, "score"), (1, "main_score"), (2, "genre"), (3, "subgenre")], default=0
                    ),
                ),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "metric",
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                ("id", bands.models_extensions.PositiveAutoField(primary_key=True, serialize=False)),
                (
                    "value",
                    bands.models_extensions.PositiveTinyIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        db_column="artist_id", on_delete=django.db.models.deletion.CASCADE, to="bands.artist"
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        db_column="metric_id", on_delete=django.db.models.deletion.CASCADE, to="bands.metric"
                    ),
                ),
            ],
            options={
                "db_table": "score",
                "unique_together": {("artist_id", "metric_id")},
            },
        ),
    ]
