# Generated by Django 5.2.4 on 2025-07-19 08:49

import django.core.validators
from django.db import migrations

import bands.models_extensions


class Migration(migrations.Migration):
    """
    Add artist.rating.
    """

    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="rating",
            field=bands.models_extensions.PositiveTinyIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
