# Generated by Django 5.2.4 on 2025-11-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0002_artist_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="category",
            field=models.CharField(max_length=255),
        ),
    ]
