# Generated by Django 5.2.8 on 2025-12-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_alter_metric_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='spotify_url',
            new_name='link_url',
        ),
    ]
