#!/bin/bash
set -e

echo "Create app user: $DATABASE_APP_USERNAME"

mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER IF NOT EXISTS '$DATABASE_APP_USERNAME'@'%' IDENTIFIED BY '$DATABASE_APP_USER_PASSWORD';"
mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT INSERT, UPDATE, DELETE, SELECT ON \`$MYSQL_DATABASE\`.* TO '$DATABASE_APP_USERNAME'@'%';"
mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;"
